version: '3.8'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - backend_data:/app/instance
    networks:
      - app_network
    mem_limit: 512M
    mem_reservation: 256M

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app_network
    mem_limit: 2G
    mem_reservation: 1G

volumes:
  backend_data:

networks:
  app_network:
    driver: bridge